[project]
name = "Farmo"
authors = []
description = ""
telemetry = false
requirements = []
[contracts.certification]
path = "contracts/certification.clar"
depends_on = []

[contracts.product-registry]
path = "contracts/product-registry.clar"
depends_on = []

[contracts.supply-chain]
path = "contracts/supply-chain.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
